### PR TITLE
Fixed misc. typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via codespell

### CODE REVIEW

**Comment by luzpaz** [comment]
@mhochsteger please review

**Comment by luzpaz** [comment]
@JSchoeberl please review

**Comment by luzpaz** [comment]
@mhochsteger / @JSchoeberl  please respond, thanks

**Comment by luzpaz** [comment]
@mhochsteger can I get access to the gitlab repo in order to submit this PR ?

**Comment by luzpaz** [comment]
@mhochsteger / @JSchoeberl

**Comment by luzpaz** [comment]
ping @mhochsteger / @JSchoeberl / @ChrLackner

**Comment by ChrLackner** [comment]
Hi, we have clarified how it is possible to contribute to Netgen/NGSolve. Please follow the [guidelines](https://github.com/NGSolve/ngsolve/blob/master/CONTRIBUTING.md) and reopen this pull request.

**Pull request closed without merging**
